version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=recipe_scraper
      - MYSQL_ROOT_PASSWORD=password

  app:
    build: .
    restart: always
    networks:
      - app-network

volumes:
  db-data:
networks:
  app-network:
